/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YourvoiceRouteImport } from './routes/yourvoice'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PageSlugRouteImport } from './routes/$pageSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSlugRouteImport } from './routes/admin.$slug'

const YourvoiceRoute = YourvoiceRouteImport.update({
  id: '/yourvoice',
  path: '/yourvoice',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PageSlugRoute = PageSlugRouteImport.update({
  id: '/$pageSlug',
  path: '/$pageSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSlugRoute = AdminSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$pageSlug': typeof PageSlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/download': typeof DownloadRoute
  '/privacy': typeof PrivacyRoute
  '/yourvoice': typeof YourvoiceRoute
  '/admin/$slug': typeof AdminSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$pageSlug': typeof PageSlugRoute
  '/download': typeof DownloadRoute
  '/privacy': typeof PrivacyRoute
  '/yourvoice': typeof YourvoiceRoute
  '/admin/$slug': typeof AdminSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$pageSlug': typeof PageSlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/download': typeof DownloadRoute
  '/privacy': typeof PrivacyRoute
  '/yourvoice': typeof YourvoiceRoute
  '/admin/$slug': typeof AdminSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$pageSlug'
    | '/admin'
    | '/download'
    | '/privacy'
    | '/yourvoice'
    | '/admin/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$pageSlug'
    | '/download'
    | '/privacy'
    | '/yourvoice'
    | '/admin/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/$pageSlug'
    | '/admin'
    | '/download'
    | '/privacy'
    | '/yourvoice'
    | '/admin/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageSlugRoute: typeof PageSlugRoute
  AdminRoute: typeof AdminRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  PrivacyRoute: typeof PrivacyRoute
  YourvoiceRoute: typeof YourvoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yourvoice': {
      id: '/yourvoice'
      path: '/yourvoice'
      fullPath: '/yourvoice'
      preLoaderRoute: typeof YourvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$pageSlug': {
      id: '/$pageSlug'
      path: '/$pageSlug'
      fullPath: '/$pageSlug'
      preLoaderRoute: typeof PageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$slug': {
      id: '/admin/$slug'
      path: '/$slug'
      fullPath: '/admin/$slug'
      preLoaderRoute: typeof AdminSlugRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSlugRoute: typeof AdminSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSlugRoute: AdminSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageSlugRoute: PageSlugRoute,
  AdminRoute: AdminRouteWithChildren,
  DownloadRoute: DownloadRoute,
  PrivacyRoute: PrivacyRoute,
  YourvoiceRoute: YourvoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
