/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YourvoiceRouteImport } from './routes/yourvoice'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PageSlugRouteImport } from './routes/$pageSlug'
import { Route as IndexRouteImport } from './routes/index'

const YourvoiceRoute = YourvoiceRouteImport.update({
  id: '/yourvoice',
  path: '/yourvoice',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PageSlugRoute = PageSlugRouteImport.update({
  id: '/$pageSlug',
  path: '/$pageSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$pageSlug': typeof PageSlugRoute
  '/privacy': typeof PrivacyRoute
  '/yourvoice': typeof YourvoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$pageSlug': typeof PageSlugRoute
  '/privacy': typeof PrivacyRoute
  '/yourvoice': typeof YourvoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$pageSlug': typeof PageSlugRoute
  '/privacy': typeof PrivacyRoute
  '/yourvoice': typeof YourvoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$pageSlug' | '/privacy' | '/yourvoice'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$pageSlug' | '/privacy' | '/yourvoice'
  id: '__root__' | '/' | '/$pageSlug' | '/privacy' | '/yourvoice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageSlugRoute: typeof PageSlugRoute
  PrivacyRoute: typeof PrivacyRoute
  YourvoiceRoute: typeof YourvoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yourvoice': {
      id: '/yourvoice'
      path: '/yourvoice'
      fullPath: '/yourvoice'
      preLoaderRoute: typeof YourvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$pageSlug': {
      id: '/$pageSlug'
      path: '/$pageSlug'
      fullPath: '/$pageSlug'
      preLoaderRoute: typeof PageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageSlugRoute: PageSlugRoute,
  PrivacyRoute: PrivacyRoute,
  YourvoiceRoute: YourvoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
